/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'circulate': RouteRecordInfo<'circulate', '/circulate', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'file': RouteRecordInfo<'file', '/file', Record<never, never>, Record<never, never>>,
    'quesForm': RouteRecordInfo<'quesForm', '/file/createFrom', Record<never, never>, Record<never, never>>,
    'qusform': RouteRecordInfo<'qusform', '/file/createFrom2', Record<never, never>, Record<never, never>>,
    'fileDetail': RouteRecordInfo<'fileDetail', '/file/detail', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'home2': RouteRecordInfo<'home2', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'circulateDetail': RouteRecordInfo<'circulateDetail', '/profile/circulateDetail', Record<never, never>, Record<never, never>>,
    'list': RouteRecordInfo<'list', '/profile/circulateList', Record<never, never>, Record<never, never>>,
    'transform': RouteRecordInfo<'transform', '/transform', Record<never, never>, Record<never, never>>,
    'createForm': RouteRecordInfo<'createForm', '/transform/createFrom', Record<never, never>, Record<never, never>>,
    'detail': RouteRecordInfo<'detail', '/transform/detail', Record<never, never>, Record<never, never>>,
    'detail2': RouteRecordInfo<'detail2', '/transform/detail2', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
